### ISSUE TITLE
Source of supernova external libraries headers?

### ISSUE THREAD

**Issue by ChristianFrisson** [mathiasbredholt/MapperUGen#2]
Hey @mathiasbredholt ,

Are these lines in CMakeLists.txt necessary?
```
if (SUPERNOVA)
    include_directories(${SC_PATH}/external_libraries/nova-tt)
    # actually just boost.atomic
    include_directories(${SC_PATH}/external_libraries/boost)
    include_directories(${SC_PATH}/external_libraries/boost_lockfree)
    include_directories(${SC_PATH}/external_libraries/boost-lockfree)
endif()
```
(block edited without `option(SUPERNOVA "Build plugins for supernova" OFF)`)

I can compile MapperUGen with `-DSUPERNOVA=ON` with supernova installed but without these external libraries headers installed on my system. Where do we find these libraries?

Kind regards,
Christian

**Comment by badebold** [comment]
Hi @ChristianFrisson 

You have to clone the main [SuperCollider](https://github.com/supercollider/supercollider/) repository, and define SC_PATH as the path of your local supercollider repo. The SuperCollider repository should be cloned with the --recursive option to clone the external libraries.

Cheers,
Mathias

**Comment by badebold** [comment]
@ChristianFrisson 

I've updated the build instructions and added supercollider as a submodule.

**Comment by ChristianFrisson** [comment]
Hey @mathiasbredholt,

Thanks for the pointer to the SuperCollider external libraries.
From this section of the CMakeLists libraries `${PROJECT}` and `${PROJECT}_supernova` rely on the same class file `${FILENAME}`.
```
add_library(${PROJECT} MODULE ${FILENAME})
target_link_libraries(${PROJECT} ${MAPPER_LIB})
Maybe that 
if(SUPERNOVA)
    add_library(${PROJECT}_supernova MODULE ${FILENAME})
    target_link_libraries(${PROJECT}_supernova ${MAPPER_LIB})
```
 Is there a motivation for having the same library compiled twice?
Note: I could compile both without the external libraries headers.

**Comment by badebold** [comment]
Yes it's because there are 2 distributions of the supercollider server, scsynth and supernova. I guess there's no reason to compile it twice though, but both files are needed.

**Comment by badebold** [comment]
The CMakeLists file is taken from sc3-plugins, and I just thought it made sense to maintain compatibility between the two projects.

**Comment by ChristianFrisson** [comment]
On my system (Ubuntu/Pop!_OS 20.04 with SC installed with apt) the `nova-tt` and `boost` external libraries headers were not needed to compile MapperUGen libraries.

**Comment by badebold** [comment]
No, but it needs the plugin API header `#include "SC_PlugIn.h"`
